name: Tasty_AI
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - blis=0.9.0
  - jupyter=1.0.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - spacy=3.7.2
  - pip:
      - tensorflow==2.10.0
