name: Tasty_AI
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.9.15
  - pip=24.2
  - jupyter=1.0.0
  - altair=5.0.1
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - seaborn=0.13.2
  - spacy=3.5.3
  - spacy-model-en_core_web_sm=3.5.0
  - scikit-learn=1.5.1
  - nltk=3.9.1
  - gensim=4.3.3
  - wordcloud=1.9.3
  - plotly=5.24.1
  - tensorflow=2.10.0
  - pip:
      - opencv-python==4.10.0.84
      - streamlit==1.40.1
