name: Tasty_AI
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.9.7
  - jupyter=1.0.0
  - matplotlib=3.9.2
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - spacy=3.5.3
  - spacy-model-en_core_web_sm=3.5.0
  - scikit-learn=1.5.1
  - nltk=3.9.1
  - gensim=4.3.3
  - pip:
      - tensorflow==2.10.0
      - opencv-python==4.10.0.84

